### ISSUE TITLE
Disambiguation functions are free to return a terminal not part of the set they are disambiguating

### ISSUE THREAD

**Issue by 602p** [melt-umn/copper#43] opened 2019-05-30 15:49 UTC
While looking at an [issue on Silver](https://github.com/melt-umn/silver/issues/304), I discovered that it doesn't seem like Copper validates that the terminal returned from a disambiguation function is one of the ones that the function ought to be disambiguate between. For example, the Silver code

```
terminal Id_t /[a-zA-Z][a-zA-Z0-9]*/;
terminal IntLit_t /[0-9]+/;
terminal If_t /if/;
ignore terminal WhiteSpace_t /[\t\r\n\ ]+/  ;

disambiguate Id_t, If_t {
  pluck IntLit_t;
}
```

produces a parser that will parse "if" as an IntLit_t. [Complete example as a Gist](https://gist.github.com/602p/3403f64fe9b264018a04d694edf049f8).

I have a [patch](https://gist.github.com/602p/ba1bd75e783a52bcf56e8d61fc0779aa) I can PR against Copper to add such a check to the site in `SingleDFAEngine` where we call `runDisambiguationAction`. Does it belong there, or in the code we generate for `runDisambiguationAction`/`disambiguate_XXX`?

**Comment by schwerdf** [comment] 2019-06-03 21:30
I thought that this had already been done as part of the new `appliesToSubsets` attribute on disambiguation functions. If a disambiguation function returns any terminal not in the match set, there should be a line in the generated parser code that catches it and returns -1. @krame505?

**Comment by krame505** [comment] 2019-06-04 05:49
That check is only applied to subset-applicable disambiguation functions.  I didn't think to add it to regular ones because the generated code for a normal disambiguation function shouldn't be accessing items from the `Terminals` enum directly.  But I suppose that since we have now decided to allow this enum to be accessed arbitrarily in action blocks, having this check is now important.  

Currently a disambiguation function returning an invalid terminal is just handled as an unresolved lexical ambiguity.  Having a better error message here would sometimes be nice, although there are cases when raising a parse error by returning an invalid terminal is the intended behavior, and we shouldn't be raising some sort of internal error.  

@602p this should be getting caught before `runDisambiguationAction` returns, anyway.  I can make a quick fix for this so that regular and subset disambiguation functions behave the same, for now.

**Closed** 2019-06-07 06:25 UTC
Labels: bug
