### ISSUE TITLE
Follow spillage error message is slightly buggy

### ISSUE THREAD

**Issue by tedinski** [melt-umn/copper#16] opened 2017-07-27 22:18 UTC
This is sort of two issues.

First, the reported spillage seems to be computed incorrectly:

```
Nonterminal edu:umn:cs:melt:ableC:concretesyntax:Constant_c has follow spillage of
    [edu:umn:cs:melt:ableC:concretesyntax:LCurly_t,
    edu:umn:cs:melt:exts:ableC:tensors:concretesyntax:Cross_product,
    edu:umn:cs:melt:exts:ableC:tensors:concretesyntax:Dot_product,
    edu:umn:cs:melt:exts:ableC:tensors:concretesyntax:Float_dot_product,
    edu:umn:cs:melt:exts:ableC:tensors:concretesyntax:Tensor_multiply]
```

This first element of the list is the only actual spillage. The other 4 are marking terminals. I hope this is just a small error in the rendering of this error message, and not something more subtle. We fixed just the curly brace, and that made this error go away, at any rate.

Second, when this kind of spillage occurs, we start with a reasonably good error message:

```
Nonterminal edu:umn:cs:melt:ableC:concretesyntax:Constant_c has follow spillage of
```

Since this tells you to go look for where your syntax uses that terminal. But then we follow it up with 147 (for spillage on expressions in AbleC) errors of this sort:

```
DFA state 880, item 0 has lookahead spillage of
```

which are both too numerous and not especially helpful. They don't even refer to state that contain the problematic production, it's seemingly just any state that can reduce to one of the problematic nonterminals.

For the moment, I think we should just eliminate reporting this second kind of error? They aren't adding anything helpful that I can see. Any actual problem should already have an error raised on the nonterminal, no?

Ideally, we'd be able to discover the _cause_ of the spillage and report that production, but I could maybe see how that'd be hard.

**Comment by schwerdf** [comment] 2017-07-29 05:26
Is there a Copper spec available for the grammar with the incorrectly reported spillage? It looks like the problem is what you say, but I would like to verify.
It is possible, although not very common, for follow and lookahead spillage to occur independently of each other (see, _e.g._, [here](../tree/develop/tests/grammars/mda)), so we cannot eliminate reporting lookahead spillage altogether, but we could possibly downgrade the messages from `QUIET` to `VERBOSE`, so they do not show in a normal run.

**Comment by tedinski** [comment] 2017-08-10 22:24
I reproduced a similar example:

[Parser_determinism_testStmt.txt](https://github.com/melt-umn/copper/files/1216537/Parser_determinism_testStmt.txt)

Here there's only one error in one production of adding `Between` to the follow set of a bunch of expression nonterminals.

A possible alternative approach to fixing the 2nd problem of too many error messages: could we suppress the lookahead spillage errors if there's also follow spillage errors? That would solve the problem, I think.

**Comment by schwerdf** [comment] 2017-08-15 05:14
This should be resolved in revision a40a9ce.
I took a hybrid approach on the lookahead spillage reporting: it is all still reported, but any that occurs in tandem with follow spillage is designated as "masked" and reported at the `VERBOSE` level.

**Closed by schwerdf** 2017-08-15 05:14 UTC

**Comment by ericvanwyk** [comment] 2017-08-17 16:48
Thanks, August.

Is this documented anywhere?

We should also have a PDF of the manual on the melt.cs.umn.edu/copper
space.  Or we could convert it to Markdown to fit into the current set up.

Any preference?

**Comment by schwerdf** [comment] 2017-08-18 05:28
No, we have no documentation of anything not accessible from the CUP skin, except for what is in the Javadoc. I was always planning to write a "Silver" skin with all the features accessible, and actually wrote the grammar and a fair number of the semantic actions, but never managed to finish it.

I think Markdown would be the best representation for the manual.

I will open issues for both these tasks.
